# Generated by Django 4.2.24 on 2026-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
