# Generated by Django 4.2.24 on 2026-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
