# Generated by Django 4.2.23 on 2026-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_scanactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_condition',
            field=models.CharField(choices=[('None', 'None'), ('Diabetes', 'Diabetes'), ('Blood Pressure', 'Blood Pressure'), ('Asthma', 'Asthma'), ('Heart Patient', 'Heart Patient'), ('Epilepsy', 'Epilepsy'), ('Allergy', 'Allergy'), ('Pregnant', 'Pregnant'), ('Other', 'Other')], default='None', max_length=30),
        ),
    ]
